name: ead-microservices

services:
  courses-db:
    image: postgres:16
    container_name: ead-courses
    environment:
      POSTGRES_DB: ead_courses_db
      POSTGRES_USER: ead_user
      POSTGRES_PASSWORD: Ead@2027!
    ports:
      - "5432:5432"
    volumes:
      - courses_data:/var/lib/postgresql/data

  authuser-db:
    image: postgres:16
    container_name: ead-authuser
    environment:
      POSTGRES_DB: ead_authuser_db
      POSTGRES_USER: ead_user
      POSTGRES_PASSWORD: Ead@2027!
    ports:
      - "5433:5432"
    volumes:
      - authuser_data:/var/lib/postgresql/data

volumes:
  courses_data:
  authuser_data: